Type: AWS::S3::Bucket
Properties:
  BucketName: ${self:custom.SpeakifyBucket.name}
  PublicAccessBlockConfiguration:
    BlockPublicAcls: true
    BlockPublicPolicy: true
    IgnorePublicAcls: true
    RestrictPublicBuckets: true
