- Effect: Allow
  Action:
    - 's3:PutObject'
    - 's3:GetObject'
    - 's3:DeleteObject'
  Resource: arn:aws:s3:::${self:custom.SpeakifyBucket.name}/*
- Effect: Allow
  Action:
    - polly:SynthesizeSpeech
  Resource: '*'
